version: "3.9"
services:
  opioner_home:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - SECRET_KEY
      - SERVER_PORT
      - NODE_ENV
    volumes:
        - opioner-data:/app

volumes:
  opioner-data: