name: Makefile CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      GITHUB_CI_TAG: ${{github.ref_name}}
      dockerHubUsername: ${{secrets.dockerHubUsername}}
      dockerHubPassword: ${{secrets.dockerHubPassword}}

    steps:
    - uses: actions/checkout@v3
      
    - name: Build docker image
      run: make build
    
    - name: Test docker image
      run: make test
    
    - name: Publish docker image
      run: make publish
      
    - name: Cleanup workspace
      run: make clean
